### ISSUE TITLE
Handling '<unnamed>' in ggetrs info

### ISSUE THREAD

**Issue by parker-insitro** [noamteyssier/ggetrs#198]
# Description

Currently ggetrs info assumes uniprot_id exists if gene name queried has match, but this causes as issue when reading in uniprot info.

How to recreate problem:

in python api:
`info = ggetrs.info(['AADACL2'])`

causes error: 
`thread '<unnamed>' panicked at src[/uniprot/functions/query.rs:75:27](http://localhost:8888/uniprot/functions/query.rs#line=74):
could not create results: Could not parse uniprot description` 

in CLI:
`ggetrs info AADACL2`

causes error:
`thread 'main' panicked at /home/ec2-user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ggetrs-0.1.78/src/uniprot/functions/query.rs:75:27:
could not create results: Could not parse uniprot description
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace`

**Comment by pgrosjean** [comment]
Ideally, instead of bailing if the UniProt query cannot be parsed, then we would instead return an empty struct so that we do not cause the async queries to fail.
